sudo: required

language: c

notifications:
  email: false

branches:
  only:
    - master
    - develop
    - "/^[0-9]+\\.[0-9]+\\.[0-9]+/"

services:
  - docker

install:
  - pip install --user cpp-coveralls

script:
  - docker run -v $(pwd):/app redborder/dev-containers:f2k ./configure
  - docker run -v $(pwd):/app redborder/dev-containers:f2k scl enable devtoolset-4 "make dynamic-sensors"
  - docker run -v $(pwd):/app redborder/dev-containers:f2k scl enable devtoolset-4 "make"
  - docker run -v $(pwd):/app -e CFLAGS=-w redborder/dev-containers:f2k scl enable devtoolset-4 "make checks -j4"

after_success:
  - docker run -v $(pwd):/app redborder/dev-containers:f2k make clean
  - docker run -v $(pwd):/app redborder/dev-containers:f2k ./configure --enable-coverage
  - docker run -v $(pwd):/app -e CFLAGS=-w redborder/dev-containers:f2k scl enable devtoolset-4 "make coverage"
  - coveralls --exclude /usr/lib --exclude tests --gcov-options '\-lp'
